---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jym.
--- DateTime: 2023/10/22 10:27
---


local upper
local a1 = 101

local function x2(a,b,x)
  if upper ~= x then
    error("up value bad " ..upper .. " " .. x)
  end
  --print("Up value ok :", upper)
  return a+b
end

function x(i)
  upper = i
  return x2(i,1,i)
end

a2 = 1

a3 = a1 + a2 + 1
a4 = x(a3)

if parent == nil then
  parent = {name="begin", okcount=0, failcount=0}
end

assert(a1 == 101)
return a1,a2,a3,a4