---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jym.
--- DateTime: 2023/10/22 10:27
---

function x(i)
  return i+1
end

local a = 99
b = 1001

c = a + b
d = x(c)
return a, b, c, d